namespace Liaison.Messaging;

using System;
using System.Collections.Concurrent;
using System.Reflection;
using Google.Protobuf;

/// <summary>
/// Serializes message payloads using Protocol Buffers generated by <c>Google.Protobuf</c>.
/// </summary>
/// <remarks>
/// This serializer requires <c>Google.Protobuf</c> generated message types. Non-protobuf
/// types throw <see cref="InvalidOperationException"/> at runtime. This is by design so
/// the serializer remains compatible with the unconstrained <see cref="IMessageSerializer"/>
/// contract used by the existing transport pipeline.
/// </remarks>
public sealed class ProtobufMessageSerializer : IMessageSerializer
{
    private static readonly ConcurrentDictionary<Type, MessageParser> Parsers = new();

    /// <summary>
    /// Serializes the provided protobuf message into protobuf wire-format bytes.
    /// </summary>
    /// <typeparam name="T">The value type. It must be a <c>Google.Protobuf</c> generated message type.</typeparam>
    /// <param name="value">The protobuf message to serialize.</param>
    /// <returns>The serialized protobuf wire-format payload.</returns>
    /// <exception cref="ArgumentNullException">Thrown when <paramref name="value"/> is <see langword="null"/>.</exception>
    /// <exception cref="InvalidOperationException">
    /// Thrown when <typeparamref name="T"/> does not implement <see cref="IMessage"/>.
    /// </exception>
    public byte[] Serialize<T>(T value)
    {
        if (value is null)
        {
            throw new ArgumentNullException(nameof(value));
        }

        if (value is not IMessage message)
        {
            throw CreateUnsupportedTypeException(typeof(T));
        }

        return message.ToByteArray();
    }

    /// <summary>
    /// Deserializes the provided protobuf wire-format payload into a generated protobuf message.
    /// </summary>
    /// <typeparam name="T">The target type. It must be a <c>Google.Protobuf</c> generated message type.</typeparam>
    /// <param name="payload">The protobuf wire-format payload to deserialize.</param>
    /// <returns>The deserialized protobuf message.</returns>
    /// <remarks>
    /// Protobuf parsing requires a contiguous byte array, so the <see cref="ReadOnlyMemory{T}"/>
    /// payload is copied before parsing. Parser reflection is cached per message type.
    /// </remarks>
    /// <exception cref="InvalidOperationException">
    /// Thrown when <typeparamref name="T"/> does not implement <see cref="IMessage"/> or does not expose a generated parser.
    /// </exception>
    public T Deserialize<T>(ReadOnlyMemory<byte> payload)
    {
        var messageType = typeof(T);
        var parser = GetParser(messageType);
        var message = parser.ParseFrom(payload.ToArray());

        return (T)message;
    }

    private static MessageParser GetParser(Type messageType)
    {
        if (!typeof(IMessage).IsAssignableFrom(messageType))
        {
            throw CreateUnsupportedTypeException(messageType);
        }

        return Parsers.GetOrAdd(messageType, ResolveParser);
    }

    private static MessageParser ResolveParser(Type messageType)
    {
        var parserProperty = messageType.GetProperty("Parser", BindingFlags.Public | BindingFlags.Static);

        if (parserProperty?.GetValue(null) is not MessageParser parser)
        {
            throw new InvalidOperationException(
                $"Type '{messageType.FullName}' does not expose a protobuf Parser.");
        }

        return parser;
    }

    private static InvalidOperationException CreateUnsupportedTypeException(Type messageType)
    {
        return new InvalidOperationException(
            "ProtobufMessageSerializer requires a Google.Protobuf message type. " +
            $"Type '{messageType.FullName}' does not implement IMessage. " +
            "Generate the type from a .proto file.");
    }
}
